/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:818abd9b-cc48-4278-b338-6770ece7be00",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wIfJGFRam",
    "aws_user_pools_web_client_id": "2aclda5e9a94jlbv6iunqnmk63",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4rwgt5l7cvhs5azwlnj2uazsaq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "reactkeymanagementred9b22b6600624ae88e4c0d3ee7d181224-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
