/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:db8fb96c-10e6-486a-a197-9a37e1940c0d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_gNT4noYZI",
    "aws_user_pools_web_client_id": "371lbrjsmig2ltg38op4bg0s2e",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5gismqam6jfnxg6mis6qllne2m.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://vyyemja6k7.execute-api.us-east-2.amazonaws.com/main",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "reactkeymanagementred9b22b6600624ae88e4c0d3ee7d234856-main",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
